version: "3.3"

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  take-my-form:
    image: take-my-form
    container_name: take-my-form
    restart: unless-stopped
    volumes:
      - </path/to/config>:/code/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.take-my-form.rule=Host(`take-my-form.example.com`)"
      - "traefik.http.routers.take-my-form.entrypoints=websecure"
      - "traefik.http.routers.take-my-form.tls.certresolver=myresolver"
      - "traefik.http.services.take-my-form.loadbalancer.server.port=80"